# Generated by Django 4.0 on 2022-01-15 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='date_of_order',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
