# Generated by Django 4.0 on 2022-01-15 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_order_date_of_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total_price',
            field=models.IntegerField(default=20, max_length=1000),
            preserve_default=False,
        ),
    ]
